# Generated by Django 4.0.3 on 2022-04-04 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('District', models.CharField(blank=True, max_length=100, null=True)),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.state')),
            ],
        ),
    ]
