# Generated by Django 4.0.3 on 2022-04-07 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_hospital_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(blank=True, max_length=100, null=True)),
                ('LastName', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.country')),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.district')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.state')),
            ],
        ),
    ]
