# Generated by Django 4.0.3 on 2022-04-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='type',
            field=models.CharField(blank=True, choices=[('Government', 'Government'), ('Private', 'Private'), ('Semi Government', 'Semi Government')], max_length=25, null=True),
        ),
    ]
