# Generated by Django 4.0.3 on 2022-04-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_hospital_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Hospital',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
