# Generated by Django 4.0.3 on 2022-04-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_doctor_main_alter_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
